In [60]:
import mlflow
from mlflow.models import infer_signature

from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
from sklearn.ensemble import RandomForestRegressor

with mlflow.start_run() as run:
    # Load the diabetes dataset.
    db = load_diabetes()
    X_train, X_test, y_train, y_test = train_test_split(db.data, db.target)

    # Create and train models.
    rf = RandomForestRegressor(n_estimators=100, max_depth=6, max_features=3)
    rf.fit(X_train, y_train)

    # Use the model to make predictions on the test dataset.
    predictions = rf.predict(X_test)
    print(predictions)

    signature = infer_signature(X_test, predictions)
    mlflow.sklearn.log_model(rf, "model", signature=signature)

    print(f"Run ID: {run.info.run_id}")


[ 91.60863735 183.51532841 132.56073006 169.74548723 109.38710684
  91.8873967  153.60027817 172.78285757 140.41406043 154.91218081
 188.90697787 127.45961423  95.03019196 167.11835818 125.48796284
  92.16406301 153.33525391 233.04203623 264.20843664 153.64811496
 184.312558   266.99663946 122.46726976 213.03087064  90.93047685
 156.1655288  218.20817779 104.09672539 172.09531621 167.38728029
 141.52894566 190.71767249  95.77397289 127.68754558 213.58494261
 218.34263236 140.69422066 204.42852979 160.80862002  91.77653797
 175.13824234 123.49138062 237.94162554 117.12257348 230.56017014
 205.83790515 205.01187406 189.62570754  96.09681171 112.31746603
  96.96269963 110.8882703  195.56109359 220.36339839 111.86307897
 184.51855948 134.34892503  96.51838405 136.41582943 121.53020929
 176.40127842 177.13342264 157.1553569   82.69463892 168.17676896
 223.40296735 221.76335438 167.76295775  95.66053876 119.80214073
 176.74705795  94.01339666 146.57798495 166.2048195  148.56333223
 124.79658

/home/jy_zhang/anaconda3/envs/env_a/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

KeyboardInterrupt



In [ ]:
import mlflow
from mlflow.models import infer_signature

from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
from sklearn.ensemble import RandomForestRegressor

mlflow.set_tracking_uri("http://127.0.0.1:8080")

with mlflow.start_run() as run:
    # Load the diabetes dataset.
    db = load_diabetes()
    X_train, X_test, y_train, y_test = train_test_split(db.data, db.target)

    # Create and train models.
    rf = RandomForestRegressor(n_estimators=100, max_depth=6, max_features=3)
    rf.fit(X_train, y_train)

    # Use the model to make predictions on the test dataset.
    predictions = rf.predict(X_test)
    print(predictions)

    signature = infer_signature(X_test, predictions)
    mlflow.sklearn.log_model(rf, "model", signature=signature)

    print(f"Run ID: {run.info.run_id}")


[104.19536386 147.25514102  91.84426681 115.80501541 157.70044376
 158.65071799 102.86626522  97.0914957  132.83355183 110.22541016
 163.32277693 253.0153023  146.96195239 180.37670036 173.90352583
 119.7895962  146.37269389 188.23106419  88.33669408 168.59123033
 106.47170419 182.3451415  255.44942373 118.48276204 131.18710908
 208.7356625  151.63915439  82.62822981  99.08058361 156.70690877
 145.25441605 117.39754791 171.3146377  230.9451768  101.02379233
 151.90895284 104.38198485 100.09255233 179.60171136 104.81741926
 170.77205692 192.93174608  92.18088478 263.97781958  95.65757008
 225.22134731  90.13179584 103.9148921  165.66134177 118.52265308
 220.30838645  84.61558267 179.13133026 112.09000491 156.78057206
 165.35991822 138.42297315 161.08177485 178.41138952 213.11511399
  95.57566294 180.39743557 121.56561795 197.67272806  83.48467499
 247.29370666 221.92175581 176.50853053 111.50459766 108.73558724
 133.13785873  98.25706647 154.94286142 193.50328359 176.49765671
 178.17246

In [ ]:
import mlflow

from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes

db = load_diabetes()
X_train, X_test, y_train, y_test = train_test_split(db.data, db.target)

model = mlflow.sklearn.load_model('runs:/cd839e2bba404761802c5f91191ae82d/')
predictions = model.predict(X_test)
print(predictions)


MlflowException: Could not find an "MLmodel" configuration file at "/tmp/tmp7z5x_38k/"

In [ ]:
import pickle
f = open('model.pkl','rb')
data = pickle.load(f)
type(data),print(data)

RandomForestRegressor(max_depth=6, min_samples_leaf=4, min_samples_split=10,
                      random_state=888)


(sklearn.ensemble._forest.RandomForestRegressor, None)

In [ ]:
import torch
data = torch.load("epoch=2-step=1290.ckpt")
data

{'epoch': 2,
 'global_step': 1290,
 'pytorch-lightning_version': '2.1.0',
 'state_dict': OrderedDict([('layer_1.weight',
               tensor([[ 0.0633,  0.0950,  0.0672,  ...,  0.0951,  0.0898,  0.0449],
                       [ 0.0761,  0.0939,  0.1276,  ...,  0.1244,  0.1177,  0.0911],
                       [-0.0055, -0.0034,  0.0207,  ...,  0.0250,  0.0401,  0.0028],
                       ...,
                       [ 0.0681,  0.0823,  0.0889,  ...,  0.0914,  0.0354,  0.0783],
                       [ 0.2150,  0.1816,  0.1800,  ...,  0.1896,  0.2103,  0.1745],
                       [ 0.0587,  0.0460,  0.0539,  ...,  0.0215,  0.0619,  0.0116]],
                      device='cuda:0')),
              ('layer_1.bias',
               tensor([-0.0605, -0.1051,  0.0227, -0.1274, -0.0625, -0.0796, -0.0308, -0.0489,
                       -0.0805, -0.0413, -0.1458, -0.0321, -0.1841, -0.0365, -0.0591, -0.0373,
                       -0.3431, -0.0860, -0.0698, -0.0624, -0.0958, -0.0166, -

In [ ]:
import onnx
data = onnx.load("model2.pth")

/home/jy_zhang/anaconda3/envs/pytorch/lib/python3.11/site-packages/onnx/__init__.py:108: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  decoded = cast(Optional[int], proto.ParseFromString(s))


DecodeError: Protobuf decoding consumed too few bytes: 5 out of 2680131

In [ ]:
import torch
torch.version.cuda, torch.backends.cudnn.version()

('11.8', 8700)

In [ ]:
torch.cuda.is_available(), torch.cuda.device_count(), torch.cuda.get_device_name()

(True, 2, 'NVIDIA GeForce RTX 4080')

In [ ]:
import tensorflow as tf
tf.test.is_gpu_available(),tf.config.list_physical_devices('GPU')

2023-11-23 15:57:42.746185: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-23 15:57:42.765074: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-23 15:57:42.765093: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-23 15:57:42.765106: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-23 15:57:42.769017: I tensorflow/core/platform/cpu_feature_g

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


2023-11-23 15:57:43.535937: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2023-11-23 15:57:43.535951: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:168] retrieving CUDA diagnostic information for host: dd-System-Product-Name
2023-11-23 15:57:43.535953: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:175] hostname: dd-System-Product-Name
2023-11-23 15:57:43.535988: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:199] libcuda reported version is: 535.129.3
2023-11-23 15:57:43.535994: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:203] kernel reported version is: 535.129.3
2023-11-23 15:57:43.535996: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:309] kernel version seems to match DSO: 535.129.3


(False, [])

In [ ]:
model_1 = tf.keras.models.load_model("model2.pth")

OSError: Unable to open file (file signature not found)

In [ ]:
import torch
with open("model2.pth", "rb") as f:
    data = f.read()
type(data)

bytes

In [ ]:
import torch
import joblib
import pickle
import tensorflow as tf

def detect_framework(model_path):
    # 尝试使用 PyTorch 加载模型
    try:
        torch.load(model_path)
        return "PyTorch"
    except (torch.nn.modules.module.ModuleAttributeError, RuntimeError, pickle.UnpicklingError):
        pass

    # 尝试使用 TensorFlow 加载模型
    try:
        tf.keras.models.load_model(model_path)
        return "TensorFlow"
    except (ValueError, AttributeError, OSError, EOFError):
        pass

    # 尝试使用 joblib 或者 pickle 加载模型
    try:
        with open(model_path, 'rb') as file:
            joblib.load(file)
        return "Scikit-learn"
    except (ValueError, AttributeError, OSError, EOFError, pickle.UnpicklingError):
        pass

    return "Unknown"

# 使用 detect_framework 函数判断模型类型
model_path = 'model2.pth'  # 替换成你的模型文件路径
framework = detect_framework(model_path)
print(f"The model is using: {framework}")


2023-11-24 15:46:18.760753: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-24 15:46:18.885845: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-24 15:46:18.885866: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-24 15:46:18.886581: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-24 15:46:18.943393: I tensorflow/core/platform/cpu_feature_g

The model is using: PyTorch


In [7]:
import torch
import torch.nn as nn

# 假设有一个模型并保存它
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.layer1 = nn.Linear(10, 20)
        self.layer2 = nn.Linear(20, 30)
        self.layer3 = nn.Linear(30, 5)
    
    def forward(self, x):
        x = torch.relu(self.layer1(x))
        x = torch.relu(self.layer2(x))
        x = self.layer3(x)
        return x

# 创建模型实例并保存
model = MyModel()
#torch.save(model.state_dict(), 'my_model.pt')



In [12]:
torch.save(model, '../my_model.pth')
isinstance(model,torch.nn.Module)

True

In [25]:
model_test = torch.load('../my_model.pt')
isinstance(model_test, dict)

True

In [29]:
help(torch.save)

Help on function save in module torch.serialization:

save(obj: object, f: Union[str, os.PathLike, BinaryIO, IO[bytes]], pickle_module: Any = <module 'pickle' from '/home/jy_zhang/anaconda3/envs/env_a/lib/python3.11/pickle.py'>, pickle_protocol: int = 2, _use_new_zipfile_serialization: bool = True) -> None
    save(obj, f, pickle_module=pickle, pickle_protocol=DEFAULT_PROTOCOL, _use_new_zipfile_serialization=True)
    
    Saves an object to a disk file.
    
    See also: :ref:`saving-loading-tensors`
    
    Args:
        obj: saved object
        f: a file-like object (has to implement write and flush) or a string or
           os.PathLike object containing a file name
        pickle_module: module used for pickling metadata and objects
        pickle_protocol: can be specified to override the default protocol
    
    .. note::
        A common PyTorch convention is to save tensors using .pt file extension.
    
    .. note::
        PyTorch preserves storage sharing across serial

In [12]:
from mlflow.utils.file_utils import TempDir
import os
local_path = '/home/jy_zhang/code'

# dir_name = os.path.basename(os.path.normpath(local_path))
# dir_name, os.path.normpath(local_path)
with TempDir() as tmp:
    print(os.path.abspath(tmp.path()))
    print("test1")
    print('test2')
    

/tmp/tmpmb81wzc2
test1
test2


In [13]:
local_path = '../pycode'
dir_name = os.path.basename(os.path.normpath(local_path))
dir_name

'pycode'

In [4]:
import abc
abc.__file__

'/home/jy_zhang/anaconda3/envs/env_a/lib/python3.11/abc.py'

In [12]:
import os

a = "mlflow-artifacts:/295829569244001181/14c2eaa75dd141b482ae9721a435e3f8/artifacts"

a = os.path.dirname(a)

a

'mlflow-artifacts:/295829569244001181/14c2eaa75dd141b482ae9721a435e3f8'

In [14]:
testdir = {'a':1, 'b':2}
testdir.get('a')

1

In [11]:
os.path.isdir('../pytorch_model.bin')

False

In [2]:
os.path.abspath('./test1.ipynb')

'/home/jy_zhang/code/pycode/test1.ipynb'

In [33]:
# 加载已保存的模型
loaded_model_state = torch.load('my_model.pt')

In [34]:
temp_model = MyModel()
temp_model_state = temp_model.state_dict()
temp_model_state

OrderedDict([('layer1.weight',
              tensor([[-0.3043, -0.1405,  0.1828, -0.1613, -0.1103, -0.1103, -0.0647,  0.2471,
                       -0.0250, -0.0297],
                      [ 0.1087, -0.2892,  0.0645,  0.1057,  0.1449,  0.2218, -0.1186,  0.2042,
                       -0.2256,  0.1482],
                      [-0.1018,  0.0414,  0.1842, -0.2359,  0.2814, -0.2790, -0.2442,  0.1207,
                        0.0629,  0.1218],
                      [-0.1345,  0.0481,  0.0255, -0.0806, -0.1713, -0.2509, -0.0230, -0.0381,
                       -0.2611, -0.2364],
                      [-0.0640,  0.1308, -0.2923, -0.1276,  0.2030, -0.0780, -0.0863, -0.0105,
                       -0.2465, -0.3130],
                      [ 0.2388, -0.2534,  0.2532, -0.3075, -0.0874,  0.1945, -0.0466, -0.0656,
                       -0.0473, -0.2508],
                      [-0.2468,  0.1568,  0.1116, -0.0136,  0.1595, -0.1011,  0.1885,  0.1895,
                        0.3063, -0.0671],
          

In [ ]:
# 更新临时模型状态字典中第一层的权重
temp_model_state['layer1.weight'] = loaded_model_state['layer1.weight']
temp_model_state['layer1.bias'] = loaded_model_state['layer1.bias']

In [ ]:
# 加载更新后的状态字典到临时模型中
temp_model.load_state_dict(temp_model_state)

<All keys matched successfully>

In [ ]:
# 现在你可以访问临时模型中的第一层权重
layer1_weights = temp_model.layer1.weight
print(layer1_weights)

Parameter containing:
tensor([[ 0.1327,  0.2410,  0.0160,  0.0796, -0.0917, -0.2165,  0.1379, -0.2588,
         -0.0418, -0.2426],
        [ 0.0121, -0.2791, -0.1170, -0.2728, -0.2103, -0.2047,  0.1350,  0.0389,
         -0.0615, -0.0656],
        [ 0.2304, -0.1965, -0.2160, -0.1875, -0.2475, -0.2976, -0.2708,  0.0793,
         -0.0839, -0.2597],
        [-0.0657, -0.1457, -0.0153,  0.2022, -0.0098, -0.2434, -0.1064,  0.1861,
         -0.3156, -0.0242],
        [-0.0724,  0.0799,  0.0811, -0.2133, -0.3034,  0.0598, -0.2264, -0.2900,
         -0.3108,  0.2913],
        [ 0.1186, -0.0654, -0.0765, -0.1273, -0.0830, -0.0324, -0.1567,  0.3038,
         -0.0756, -0.1254],
        [-0.1813, -0.1068, -0.0429, -0.0960, -0.0951, -0.2517,  0.0334,  0.3103,
          0.2028,  0.0773],
        [-0.0661, -0.2851, -0.2932, -0.1070,  0.1101, -0.1198,  0.0904,  0.1695,
         -0.3161, -0.0128],
        [ 0.1358,  0.3056,  0.2715,  0.1985,  0.2016, -0.0567,  0.0483, -0.1020,
          0.2979,  0.1270

In [ ]:
loaded_model_state['layer1.weight'] == temp_model.state_dict()['layer1.weight'],loaded_model_state['layer1.bias'] == temp_model.state_dict()['layer1.bias']

(tensor([[True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
      

In [ ]:
loaded_model_state['layer2.weight'] == temp_model.state_dict()['layer2.weight']

tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, Fa

In [ ]:
torch.tensor(temp_model.layer1.weight.data.numpy())  == temp_model.layer1.weight

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True,

In [ ]:
help(temp_model.layer1.weight)

Help on Parameter in module torch.nn.parameter object:

class Parameter(torch.Tensor)
 |  Parameter(data=None, requires_grad=True)
 |  
 |  A kind of Tensor that is to be considered a module parameter.
 |  
 |  Parameters are :class:`~torch.Tensor` subclasses, that have a
 |  very special property when used with :class:`Module` s - when they're
 |  assigned as Module attributes they are automatically added to the list of
 |  its parameters, and will appear e.g. in :meth:`~Module.parameters` iterator.
 |  Assigning a Tensor doesn't have such effect. This is because one might
 |  want to cache some temporary state, like last hidden state of the RNN, in
 |  the model. If there was no such class as :class:`Parameter`, these
 |  temporaries would get registered too.
 |  
 |  Args:
 |      data (Tensor): parameter tensor.
 |      requires_grad (bool, optional): if the parameter requires gradient. See
 |          :ref:`locally-disable-grad-doc` for more details. Default: `True`
 |  
 |  Metho

In [ ]:
len(temp_model.layer1.weight.shape),temp_model.layer1.weight.shape,

(2, torch.Size([20, 10]))

In [ ]:
import hashlib
import numpy

weights = temp_model.layer1.weight.data
block1 = temp_model.layer1.weight.data.numpy()
block2 = loaded_model_state['layer1.weight'].numpy()

block_hash1 = hashlib.sha256(block1.tobytes()).hexdigest()
block_hash2 = hashlib.sha256(block2.tobytes()).hexdigest()

block_hash1 == block_hash2, type(block_hash2)

(True, str)

In [67]:
import h5py
import os

hdf5_file_path = block_hash1
dirs = "./block_files/TEST"
file_name = os.path.join(dirs,hdf5_file_path+".h5")

if not os.path.exists(dirs):
    os.makedirs(dirs)
    print("Dir create.")
else:
    print("Dir exist.")  
    
if not os.path.exists(file_name):
    with h5py.File(file_name, 'w') as hf:
        hf.create_dataset('weights', data=weights)
    print("File create.")
else:
    print("File exist.")
    
            
            
# if os.path.exists(dirs) and os.path.exists(file_name):
#     print("Dir exists.")
# else:
#     if not os.path.exists(file_name):
#         with h5py.File(file_name, 'w') as hf:
#             hf.create_dataset('weights', data=weights) 
#         print("File creates.")

Dir create.
File create.


In [ ]:
temp_model.layer1.weight.data[3]

tensor([-0.0657, -0.1457, -0.0153,  0.2022, -0.0098, -0.2434, -0.1064,  0.1861,
        -0.3156, -0.0242])

In [89]:
for k,v in temp_model_state.items():
    print(v.shape)

torch.Size([20, 10])
torch.Size([20])
torch.Size([30, 20])
torch.Size([30])
torch.Size([5, 30])
torch.Size([5])


In [77]:
for i in range(0, 2, 16):
    print(i)

0


In [82]:
temp_model.layer1.weight.data.shape[0]

20

In [88]:
weights[0:1,9:19492]

tensor([[-0.2426]])

In [5]:
import os
file_path = "./adad/adada/my_model.pt"
file_name = os.path.splitext(os.path.basename(file_path))[0]
file_name


'my_model'

In [64]:
a = 'layer2'
b = temp_model.state_dict()['layer1.weight'].shape
with open('hash_info.txt', 'a') as file:
    file.write("[s]")
    file.write(f"{a}:{b}\n")

In [29]:
with open('hash_info.txt', 'r') as file:
    for line in file:
        line = line.strip()
        parts = line.split(':')
        layer = parts[0]
        print(f"layer name is {layer}.")
        has_value = parts[1][1:-1].split(',')
        for i in range(len(has_value)):
            has_value[i] = has_value[i][2:-2]
        print(f"hash value are {has_value}.")

layer name is layer1.
hash value are ['fdfsfwe23', 'fef33'].
layer name is layer2.
hash value are ['adsada', 'fef33'].
layer name is layer2.
hash value are ['adsada', 'fef33'].


In [12]:
type(data)

str

In [26]:
str = "['sfdfsfwe232', 'fef332']"
str = str[1:-1]
str

"'sfdfsfwe232', 'fef332'"

In [35]:
temp_model.state_dict()

OrderedDict([('layer1.weight',
              tensor([[-0.3043, -0.1405,  0.1828, -0.1613, -0.1103, -0.1103, -0.0647,  0.2471,
                       -0.0250, -0.0297],
                      [ 0.1087, -0.2892,  0.0645,  0.1057,  0.1449,  0.2218, -0.1186,  0.2042,
                       -0.2256,  0.1482],
                      [-0.1018,  0.0414,  0.1842, -0.2359,  0.2814, -0.2790, -0.2442,  0.1207,
                        0.0629,  0.1218],
                      [-0.1345,  0.0481,  0.0255, -0.0806, -0.1713, -0.2509, -0.0230, -0.0381,
                       -0.2611, -0.2364],
                      [-0.0640,  0.1308, -0.2923, -0.1276,  0.2030, -0.0780, -0.0863, -0.0105,
                       -0.2465, -0.3130],
                      [ 0.2388, -0.2534,  0.2532, -0.3075, -0.0874,  0.1945, -0.0466, -0.0656,
                       -0.0473, -0.2508],
                      [-0.2468,  0.1568,  0.1116, -0.0136,  0.1595, -0.1011,  0.1885,  0.1895,
                        0.3063, -0.0671],
          

In [68]:
for k,v in temp_model.state_dict().items():
    print(len(v.data.shape))
    print((list(v.shape)))
    # print(type(k))
    # print(f"{k},{v}")

2
[20, 10]
1
[20]
2
[30, 20]
1
[30]
2
[5, 30]
1
[5]


In [59]:
for i in temp_model.state_dict()['layer1.weight'].shape:
    print(i)

20
10


In [62]:
print(temp_model.state_dict()['layer1.weight'].shape)

torch.Size([20, 10])


In [65]:
list(temp_model.state_dict()['layer1.weight'].shape)

[20, 10]

In [69]:
a = [12,323]
type(a),a

(list, [12, 323])

In [15]:
model_shape = {}
with open('my_model.txt','r') as file:
    
    for line in file:
        #print(line[3:])
        if line[1] == 's':
            line = line[3:]
            line = line.strip()
            parts = line.split(':')
            layer = parts[0]
            print(f"layer name is {layer}.")
            data = parts[1][1:-1].split(',')
            layer_shape = []
            for i in data:
                # i = i.strip()
                layer_shape.append(int(i))
            model_shape[layer] = layer_shape
            print(f"{layer} : {layer_shape}.")
            # for i in range(len(has_value)):
            #     has_value[i] = has_value[i][2:-2]
            #print(f"hash value are {has_value}.")
            # print(type(line[1]))

layer name is layer1.weight.
layer1.weight : [20, 10].
layer name is layer1.bias.
layer1.bias : [20].
layer name is layer2.weight.
layer2.weight : [30, 20].
layer name is layer2.bias.
layer2.bias : [30].
layer name is layer3.weight.
layer3.weight : [5, 30].
layer name is layer3.bias.
layer3.bias : [5].


In [36]:
model_shape = {}
with open('my_model.txt','r') as file:
    
    for line in file:
        # print(line[3:])
        if line[1] == 'p':
            line = line[3:]
            line = line.strip()
            parts = line.split(':')
            layer = parts[0]
            print(f"layer name is {layer}.")
            data = parts[1][1:-1].split(',')
            hash_value = []
            for i in data:
                hash_value.append(i.strip()[1:-1])
                #print(i[1:-1])
            print(f"{layer} : {hash_value[0]}.")
            # model_state[layer] = hash_value
            # for i in range(len(has_value)):
            #     has_value[i] = has_value[i][2:-2]
            #print(f"hash value are {has_value}.")
            # print(type(line[1]))

layer name is layer1.weight.
layer1.weight : 49a1bd60405f7ced4579f456bf8f5be7b8f6e96e17cd0b68c0272ba9d676919a.
layer name is layer1.bias.
layer1.bias : 3dabdefacea5de81bc5ab876106e967ba270c75d73b8d0a1054e890e882033db.
layer name is layer2.weight.
layer2.weight : c88df49ba9805e92c85c7f5ad4e460c9a18514d39373ec67f65a2f6ac889daca.
layer name is layer2.bias.
layer2.bias : 13d078649dd685acfcc8535154d8f247859154d52136a34a47b1fad017b57c83.
layer name is layer3.weight.
layer3.weight : d1398b89a7eaf80667f59340c816ea757adabdffd5fdf4dc6826e3aa923fe950.
layer name is layer3.bias.
layer3.bias : b2eb4ce261a762e739c6d6f773d5478363b74c4eb85f6250f9457abe67b29212.


In [20]:
import torch
model = torch.load("pytorch_model.bin")

OrderedDict([('wav2vec2.masked_spec_embed',
              tensor([ 0.5507,  0.4647, -0.8060,  ...,  0.5205, -0.4617, -0.2501],
                     device='cuda:0')),
             ('wav2vec2.feature_extractor.conv_layers.0.conv.weight',
              tensor([[[-0.0301,  0.0601, -0.0824,  ...,  0.1017, -0.0714,  0.0293]],
              
                      [[-0.0608,  0.2048, -0.3384,  ..., -0.2467,  0.1772, -0.0568]],
              
                      [[-0.0760,  0.1932, -0.2710,  ...,  0.1458, -0.0731,  0.0205]],
              
                      ...,
              
                      [[ 0.0909, -0.0269, -0.0012,  ...,  0.2131, -0.2964, -0.1357]],
              
                      [[-0.0822,  0.0698,  0.0471,  ...,  0.0196, -0.0282,  0.0362]],
              
                      [[ 0.0054, -0.0195,  0.0404,  ...,  0.0238,  0.0038, -0.0026]]],
                     device='cuda:0')),
             ('wav2vec2.feature_extractor.conv_layers.0.conv.bias',
              tensor(

In [34]:
for k,v in model.items():
    print(k)

wav2vec2.masked_spec_embed
wav2vec2.feature_extractor.conv_layers.0.conv.weight
wav2vec2.feature_extractor.conv_layers.0.conv.bias
wav2vec2.feature_extractor.conv_layers.0.layer_norm.weight
wav2vec2.feature_extractor.conv_layers.0.layer_norm.bias
wav2vec2.feature_extractor.conv_layers.1.conv.weight
wav2vec2.feature_extractor.conv_layers.1.conv.bias
wav2vec2.feature_extractor.conv_layers.1.layer_norm.weight
wav2vec2.feature_extractor.conv_layers.1.layer_norm.bias
wav2vec2.feature_extractor.conv_layers.2.conv.weight
wav2vec2.feature_extractor.conv_layers.2.conv.bias
wav2vec2.feature_extractor.conv_layers.2.layer_norm.weight
wav2vec2.feature_extractor.conv_layers.2.layer_norm.bias
wav2vec2.feature_extractor.conv_layers.3.conv.weight
wav2vec2.feature_extractor.conv_layers.3.conv.bias
wav2vec2.feature_extractor.conv_layers.3.layer_norm.weight
wav2vec2.feature_extractor.conv_layers.3.layer_norm.bias
wav2vec2.feature_extractor.conv_layers.4.conv.weight
wav2vec2.feature_extractor.conv_layers.4

In [25]:
test_str = "[1024]"
data = test_str.split(',')

In [26]:
data

['[1024]']

In [32]:
print(data[0][1:-1])

1024


In [39]:
import os
os.path.join("./block_files/speech_recognition/pickle","4d809a89d92f7d135c207c8647df3b547ab4db2d0c4539fece4b69191e193273"+".pkl")

'./block_files/speech_recognition/pickle/4d809a89d92f7d135c207c8647df3b547ab4db2d0c4539fece4b69191e193273.pkl'

In [42]:
import pickle
with open("block_files/pickle/3dabdefacea5de81bc5ab876106e967ba270c75d73b8d0a1054e890e882033db.pkl","rb") as file:
    data = pickle.load(file)
data

tensor([ 0.1065,  0.3041, -0.2950,  0.2020,  0.2700,  0.1962, -0.1835,  0.0407,
         0.2676,  0.0689,  0.0622,  0.1616, -0.2105,  0.1931, -0.1889, -0.2771,
        -0.2254, -0.1926, -0.0225, -0.0096])

In [84]:
origin = torch.load("pytorch_model.bin")
compose = torch.load("pytorch_model_compose.pt")
# origin == compose
len(origin), len(compose)

(424, 424)

In [85]:
len(origin) == len(compose)

True

In [53]:
origin[1]

KeyError: 1

In [54]:
for io,ic in origin.items(),compose.items():
    print(io,ic)
origin

ValueError: too many values to unpack (expected 2)

In [68]:
origin.keys() == compose.keys()

True

In [86]:
origin.values() == compose.values()

False

In [87]:
origin.values()

odict_values([tensor([ 0.5507,  0.4647, -0.8060,  ...,  0.5205, -0.4617, -0.2501],
       device='cuda:0'), tensor([[[-0.0301,  0.0601, -0.0824,  ...,  0.1017, -0.0714,  0.0293]],

        [[-0.0608,  0.2048, -0.3384,  ..., -0.2467,  0.1772, -0.0568]],

        [[-0.0760,  0.1932, -0.2710,  ...,  0.1458, -0.0731,  0.0205]],

        ...,

        [[ 0.0909, -0.0269, -0.0012,  ...,  0.2131, -0.2964, -0.1357]],

        [[-0.0822,  0.0698,  0.0471,  ...,  0.0196, -0.0282,  0.0362]],

        [[ 0.0054, -0.0195,  0.0404,  ...,  0.0238,  0.0038, -0.0026]]],
       device='cuda:0'), tensor([-0.0115, -0.0240, -0.0242, -0.0116, -0.0116, -0.0115, -0.0226, -0.0405,
        -0.0252, -0.0504, -0.0115, -0.0115, -0.0113, -0.0119, -0.0114, -0.0120,
        -0.0186, -0.0115, -0.0113, -0.0115, -0.0119, -0.0117, -0.0217, -0.0231,
        -0.0044, -0.0116, -0.0122, -0.0116, -0.0117, -0.0440, -0.0117, -0.0105,
        -0.0052, -0.0637, -0.0079, -0.0114, -0.0314, -0.0117, -0.0029, -0.0120,
        -0.0118

In [91]:
for key in origin.keys():
    if key in compose.keys():
        if not torch.equal(origin[key], compose[key]):
            print(f"Difference found in key: {key}")
            print(f"Values for {key} in origin: {origin[key]}")
            print(f"Values for {key} in compose: {compose[key]}")
    else:
        print(f"Key '{key}' not found in compose")
        
for key in compose.keys():
    if key not in origin.keys():
        print(f"Key '{key}' not found in origin")

i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i
i


In [77]:
origin.keys() == compose.keys()

True

In [2]:
import torch
torch.cuda.is_available()

True

In [5]:
import mlflow.pytorch
mlflow.pytorch.__file__

'/home/jy_zhang/anaconda3/envs/env_a/lib/python3.11/site-packages/mlflow/pytorch/__init__.py'

In [1]:
import mlflow.models

test = mlflow.models

test.__file__

'/home/jy_zhang/anaconda3/envs/env_a/lib/python3.11/site-packages/mlflow/models/__init__.py'

In [2]:
test = mlflow.models

import test

mlflow.models.__file__

NameError: name 'mlflow' is not defined

In [6]:
import torch
model = torch.load("../my_model.pt")
isinstance(model,torch.nn.Module)

False